extends:
  - eslint:recommended
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
plugins:
  - jest
env:
  es6: true
  node: true
  jest/globals: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
